ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "position" TEXT;
ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "position2" TEXT;
ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "age" DOUBLE PRECISION;
ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "employmentStart" TIMESTAMP(3);
ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "employmentEnd" TIMESTAMP(3);
ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "screamEligible" BOOLEAN NOT NULL DEFAULT true;

CREATE INDEX IF NOT EXISTS "Staff_active_screamEligible_idx" ON "Staff"("active", "screamEligible");
